spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  access:
    token:
      expiration: 3600000
  refresh:
    token:
      expiration: 604800000

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET:}
  redirect:
    url: ${KAKAO_REDIRECT_URL}

fcm:
  private-key: ${FCM_PRIVATE_KEY}

recommendation:
  limit:
    active-recommendations: 10
    candidate: 100
  saved-replies: 5

scheduler:
  batch-size: 50
  parallelism: 4

slack:
  token: ${SLACK_TOKEN:dummy}
